name: Lint

on: push

env:
  NODE_VERSION: 21

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install yarn
        run: npm i -g yarn

      - name: Install Dependencies
        run: yarn

      - name: Code Linting
        run: yarn lint
